// Generated by CoffeeScript 1.9.2
(function() {
  var _;

  _ = {
    once: function(fn) {
      var invoked, result;
      invoked = false;
      result = void 0;
      return function() {
        if (!invoked) {
          invoked = true;
          result = fn();
        }
        return result;
      };
    },
    memoize: function(fn, cache_key) {
      var cache;
      cache = {};
      return function(parameter) {
        var hash_key;
        hash_key = parameter;
        if (cache_key !== void 0) {
          hash_key = cache_key(parameter);
        }
        if (cache.hasOwnProperty(hash_key)) {
          return cache[hash_key];
        } else {
          return cache[hash_key] = fn(parameter);
        }
      };
    },
    bind: function(fn, context) {
      return function() {
        return fn.apply(context);
      };
    }
  };

  module.exports = _;

}).call(this);
